### PR TITLE
Enhancement - Upgrade encryption

### PR DESCRIPTION
**Pull request by SanchitJain123**
RSA Encyption on the AES encryption key is implemented
This fixes issue #11

### CODE REVIEW

**Comment by rexdivakar** [comment]
Hey @SanchitJain123  Can u please add in screenshots of the keys and encrypted files to support the action

**Comment by SanchitJain123** [comment]
> 
> 
> Hey @SanchitJain123 Can u please add in screenshots of the keys and encrypted files to support the action

@rexdivakar should I add just add screenshots or update README as well?

**Comment by rexdivakar** [comment]
Please add the changes to the readme file as well as attach a screenshot of the keys and the encrypted files to approve the PR

**Comment by SanchitJain123** [comment]
> 
> 
> Please add the changes to the readme file as well as attach a screenshot of the keys and the encrypted files to approve the PR

Sure

**Comment by SanchitJain123** [comment]
@rexdivakar can you please add "hacktoberfest" as topic to the repository or "hacktoberfest-accepted" label to the PR such that the PR gets accepted for the hacktoberfest.

**Comment by SanchitJain123** [comment]
`Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.`

**Pull request merged**
