### PR TITLE
fix-key-overriding

### PR DESCRIPTION
**Pull request by SanchitJain123**
If key.pem already existed then its contents was getting overrided and
some left over bytes were corrupting the key data. Removed key.pem file
before saving key.pem file. Fixed some typos.
Fixes issue in #15

### CODE REVIEW

**Comment by SanchitJain123** [comment]
@rexdivakar can you please check now if it's working?

**Comment by rexdivakar** [comment]
hey buddy the problem is It's not able to decrypt the code back,

image

**Comment by SanchitJain123** [comment]
@rexdivakar very strange it's working on my machine. Can you please tell the steps to reproduce the issue, it would be helpful because its working fine in my machine. I had tried both file decryption as well as folder decryption.

**Comment by SanchitJain123** [comment]
@rexdivakar after this commit there should not be any problem. I'll post screenshot of the decryption after this commit here just to be sure the steps you are following are same.

**Comment by SanchitJain123** [comment]
Output

**Comment by SanchitJain123** [comment]
@rexdivakar the problem of the decryption failure was that the `key.pem` file was getting overridden by the contents of the new key. Because the old `key.pem` already existed the contents were getting mixed (old + new) and the key was getting hampered, that is why the decryption was failing in folder maybe the `key.pem` already existed during the encryption process. That is why i have added a check to delete `key.pem` file if its already exists in the current folder during the encryption process. This commit/PR should solve it.

**Review by rexdivakar — APPROVED** [review]

**Comment by rexdivakar** [comment]
Great job buddy, u fixed it !! @SanchitJain123

**Pull request merged**
