### PR TITLE
Documentation for tool

### LINKED ISSUE #9: Creating proper documentation

### PR DESCRIPTION
**Pull request by Tawishi**
- [x] Readme
- [x] Work structure (in Readme)
- [x] requirements.txt
Closes #9

### CODE REVIEW

**Comment by Tawishi** [comment]
@rexdivakar please review and suggest changes, if any.

**Review by rexdivakar — APPROVED** [review]
Great job

**Comment by Tawishi** [comment]
> Great job

Thank you @rexdivakar for your help all along.

**Comment by rexdivakar** [comment]
Closing the issue, feel free to join in and collaborate onto other repo's

🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/59TDJgt

**Pull request merged**
